// Generated by `cargo run -p bindings-gen`. Do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct NewDesignLayerDefaults {
    pub(crate) name: &'static str,
    pub(crate) visible: bool,
    pub(crate) locked: bool,
    pub(crate) opacity: f32,
}

pub(crate) fn new_design_spatial_frame() -> common_types::design::SpatialFrame {
    common_types::design::SpatialFrame {
        anchor_longitude_deg: 13.0_f64,
        anchor_latitude_deg: 23.0_f64,
        north_bearing_deg: 0.0_f64,
        placement_status: common_types::design::PlacementStatus::Provisional,
        location_metadata: common_types::design::LocationMetadata { altitude_m: None },
    }
}

pub(crate) const NEW_DESIGN_LAYER_DEFAULTS: &[NewDesignLayerDefaults] = &[
    NewDesignLayerDefaults {
        name: "base",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "contours",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "climate",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "zones",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "water",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "plants",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "measurement-guides",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "annotations",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
];
