// Generated by `cargo run -p bindings-gen`. Do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct NewDesignLayerDefaults {
    pub(crate) name: &'static str,
    pub(crate) visible: bool,
    pub(crate) locked: bool,
    pub(crate) opacity: f32,
}

pub(crate) const NEW_DESIGN_NORTH_BEARING_DEG: Option<f64> = None;

pub(crate) const NEW_DESIGN_LAYER_DEFAULTS: &[NewDesignLayerDefaults] = &[
    NewDesignLayerDefaults {
        name: "base",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "contours",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "climate",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "zones",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "water",
        visible: false,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "plants",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "measurement-guides",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
    NewDesignLayerDefaults {
        name: "annotations",
        visible: true,
        locked: false,
        opacity: 1.0_f32,
    },
];
