use specta::TypeCollection;
use specta_typescript::{BigIntExportBehavior, SerdeMode, Typescript};

pub(crate) fn render_typescript_contracts() -> Result<String, Box<dyn std::error::Error>> {
    let types = TypeCollection::default()
        .register::<common_types::design::Annotation>()
        .register::<common_types::design::LoadedDesign>()
        .register::<common_types::design::DesignSaveOutcome>()
        .register::<common_types::design::DesignDraftSummary>()
        .register::<common_types::design::BudgetItem>()
        .register::<common_types::design::CanopiFile>()
        .register::<common_types::design::Consortium>()
        .register::<common_types::design::DesignNotebookEntry>()
        .register::<common_types::design::DesignNotebookSection>()
        .register::<common_types::design::DesignNotebookSnapshot>()
        .register::<common_types::design::DesignSummary>()
        .register::<common_types::design::Layer>()
        .register::<common_types::design::ObjectGroup>()
        .register::<common_types::design::PanelTarget>()
        .register::<common_types::design::PlacedPlant>()
        .register::<common_types::design::GeoPoint>()
        .register::<common_types::design::SpeciesPanelTarget>()
        .register::<common_types::design::SpeciesPanelTargetKind>()
        .register::<common_types::design::TimelineAction>()
        .register::<common_types::design::Zone>()
        .register::<common_types::health::PlantDbStatus>()
        .register::<common_types::health::SubsystemHealth>()
        .register::<common_types::library::AnalysisInputBinding>()
        .register::<common_types::library::AnalysisJobState>()
        .register::<common_types::library::AnalysisOffer>()
        .register::<common_types::library::AnalysisParamValue>()
        .register::<common_types::library::AnalysisReceipt>()
        .register::<common_types::library::AnalysisRequest>()
        .register::<common_types::library::AnalysisRunStatus>()
        .register::<common_types::library::AnalysisUnavailable>()
        .register::<common_types::library::Freshness>()
        .register::<common_types::library::LibraryDeleteImpact>()
        .register::<common_types::library::LibraryEngines>()
        .register::<common_types::library::LibraryItemRole>()
        .register::<common_types::library::LibraryItemSummary>()
        .register::<common_types::library::LibraryItemType>()
        .register::<common_types::library::LibrarySnapshot>()
        .register::<common_types::library::ParamValue>()
        .register::<common_types::library::ProcessingHistoryPage>()
        .register::<common_types::library::ProcessingRun>()
        .register::<common_types::library::ProcessingRunOutput>()
        .register::<common_types::library::Provenance>()
        .register::<common_types::library::ProvenanceInput>()
        .register::<common_types::library::RasterQuantity>()
        .register::<common_types::library::StaleReason>()
        .register::<common_types::library::ToolProvenance>()
        .register::<common_types::lidar::LidarDisplayAsset>()
        .register::<common_types::lidar::LidarDisplayDescriptor>()
        .register::<common_types::lidar::LidarDisplayRequest>()
        .register::<common_types::lidar::LidarDisplayState>()
        .register::<common_types::lidar::LidarEngineStatus>()
        .register::<common_types::lidar::LidarImportJob>()
        .register::<common_types::lidar::LidarImportReceipt>()
        .register::<common_types::lidar::LidarImportJobState>()
        .register::<common_types::lidar::LidarLayerCollection>()
        .register::<common_types::lidar::LidarLayerSource>()
        .register::<common_types::lidar::LidarPresentationEntry>()
        .register::<common_types::lidar::LidarPresentationEntryKind>()
        .register::<common_types::lidar::LidarPresentationSection>()
        .register::<common_types::lidar::LidarResultState>()
        .register::<common_types::lidar::LidarSampleOutcome>()
        .register::<common_types::lidar::LidarSampleRequest>()
        .register::<common_types::lidar::LidarSampleUnavailableReason>()
        .register::<common_types::location::GeoResult>()
        .register::<common_types::saved_object_stamps::SavedObjectStamp>()
        .register::<common_types::settings::LastView>()
        .register::<common_types::settings::Locale>()
        .register::<common_types::settings::Settings>()
        .register::<common_types::settings::Theme>()
        .register::<common_types::support::FrontendDiagnosticEntry>()
        .register::<common_types::support::ProblemReportRequest>()
        .register::<common_types::support::ProblemReportResult>()
        .register::<common_types::species::CommonNameEntry>()
        .register::<common_types::species::DynamicFilter>()
        .register::<common_types::species::DynamicFilterOptions>()
        .register::<common_types::species::FilterOp>()
        .register::<common_types::species::FilterOptions>()
        .register::<common_types::species::FilterValue>()
        .register::<common_types::species::FlowerColorResolution>()
        .register::<common_types::species::PaginatedResult<common_types::species::SpeciesListItem>>(
        )
        .register::<common_types::species::Sort>()
        .register::<common_types::species::SpeciesDetail>()
        .register::<common_types::species::SpeciesFilter>()
        .register::<common_types::species::SpeciesImage>()
        .register::<common_types::species::SpeciesListItem>()
        .register::<common_types::species::SpeciesSearchRequest>()
        .register::<common_types::species::SpeciesUse>();

    let rendered = Typescript::default()
        .header("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.")
        .bigint(BigIntExportBehavior::String)
        .with_serde(SerdeMode::Serialize)
        .export(&types)?;
    // The TypeScript exporter leaves a trailing space on multi-line union
    // heads. Normalize here rather than hand-editing a generated file, so the
    // committed output passes the repository's whitespace check and stays
    // byte-identical to what regeneration produces.
    let mut normalized: String = rendered
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    Ok(normalized)
}
