use std::collections::BTreeSet;
use std::fmt::Write as _;

pub(crate) fn render_known_canopi_keys() -> Result<String, Box<dyn std::error::Error>> {
    let mut file =
        String::from("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n");
    writeln!(
        file,
        "export const DEFAULT_BUDGET_CURRENCY = {:?}\n",
        common_types::design::DEFAULT_BUDGET_CURRENCY,
    )?;
    writeln!(
        file,
        "export const DEFAULT_PLANT_SYMBOL_ID = {:?}\n",
        common_types::design::DEFAULT_PLANT_SYMBOL_ID,
    )?;
    file.push_str("export const PLANT_SYMBOL_IDS = [\n");
    for symbol in common_types::design::PLANT_SYMBOL_IDS {
        writeln!(file, "  {:?},", symbol)?;
    }
    file.push_str("] as const\n");
    file.push_str("export type PlantSymbolId = (typeof PLANT_SYMBOL_IDS)[number]\n\n");

    file.push_str("export const KNOWN_CANOPI_KEYS = [\n");
    for field in common_types::design::DESIGN_FILE_FIELDS {
        writeln!(file, "  {:?},", field.key)?;
    }
    file.push_str("] as const\n");
    file.push_str("\nexport type KnownCanopiKey = (typeof KNOWN_CANOPI_KEYS)[number]\n");
    file.push_str("export type DocumentFileFieldOwner = 'document' | 'scene' | 'shared'\n\n");
    file.push_str("export const DOCUMENT_FILE_FIELD_OWNERS = {\n");
    for field in common_types::design::DESIGN_FILE_FIELDS {
        writeln!(file, "  {}: {:?},", field.key, field.owner.as_str())?;
    }
    file.push_str("} as const satisfies Record<KnownCanopiKey, DocumentFileFieldOwner>\n");
    Ok(file)
}

pub(crate) fn render_canopi_design_format() -> Result<String, Box<dyn std::error::Error>> {
    let schema = common_types::design::canopi_file_json_schema();
    validate_canopi_design_schema(&schema)?;
    let schema_json = serde_json::to_string_pretty(&schema)?;
    let mut file =
        String::from("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n");
    writeln!(
        file,
        "export const CURRENT_CANOPI_FILE_VERSION = {}\n",
        common_types::design::CURRENT_CANOPI_FILE_VERSION,
    )?;
    writeln!(
        file,
        "export const CANOPI_FILE_SCHEMA = {schema_json} as const"
    )?;
    Ok(file)
}

fn validate_canopi_design_schema(
    schema: &serde_json::Value,
) -> Result<(), Box<dyn std::error::Error>> {
    let properties = schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
        .ok_or("generated CanopiFile schema has no root properties")?;
    let actual = properties
        .keys()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    let expected = common_types::design::DESIGN_FILE_FIELDS
        .iter()
        .map(|field| field.key)
        .filter(|key| *key != "extra")
        .collect::<BTreeSet<_>>();
    if actual != expected {
        return Err(format!(
            "generated CanopiFile schema fields differ from DESIGN_FILE_FIELDS: expected {expected:?}, got {actual:?}",
        )
        .into());
    }
    if schema.get("additionalProperties") != Some(&serde_json::Value::Bool(true)) {
        return Err(
            "generated CanopiFile schema must preserve flattened unknown root fields".into(),
        );
    }
    validate_supported_canopi_schema_node(schema, "$schema")?;
    Ok(())
}

fn validate_supported_canopi_schema_node(
    schema: &serde_json::Value,
    path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    const SUPPORTED_KEYWORDS: &[&str] = &[
        "$defs",
        "$ref",
        "$schema",
        "additionalProperties",
        "anyOf",
        "const",
        "default",
        "enum",
        "format",
        "items",
        "minimum",
        "oneOf",
        "properties",
        "required",
        "title",
        "type",
    ];

    let object = schema
        .as_object()
        .ok_or_else(|| format!("{path}: generated schema node is not an object"))?;
    for keyword in object.keys() {
        if !SUPPORTED_KEYWORDS.contains(&keyword.as_str()) {
            return Err(format!(
                "{path}: generated Canopi schema keyword {keyword} is not supported by the Web decoder",
            )
            .into());
        }
    }
    if let Some(format) = object.get("format") {
        const SUPPORTED_FORMATS: &[&str] = &["double", "float", "int32", "uint32"];
        let format = format
            .as_str()
            .ok_or_else(|| format!("{path}: generated schema format is not a string"))?;
        if !SUPPORTED_FORMATS.contains(&format) {
            return Err(format!(
                "{path}: generated Canopi schema format {format} is not supported by the Web decoder",
            )
            .into());
        }
    }

    for (container_key, container) in [
        ("$defs", object.get("$defs")),
        ("properties", object.get("properties")),
    ] {
        let Some(entries) = container.and_then(serde_json::Value::as_object) else {
            continue;
        };
        for (key, child) in entries {
            validate_supported_canopi_schema_node(child, &format!("{path}.{container_key}.{key}"))?;
        }
    }
    for keyword in ["items", "additionalProperties"] {
        if let Some(child) = object.get(keyword).filter(|child| child.is_object()) {
            validate_supported_canopi_schema_node(child, &format!("{path}.{keyword}"))?;
        }
    }
    for keyword in ["anyOf", "oneOf"] {
        let Some(children) = object.get(keyword).and_then(serde_json::Value::as_array) else {
            continue;
        };
        for (index, child) in children.iter().enumerate() {
            validate_supported_canopi_schema_node(child, &format!("{path}.{keyword}[{index}]"))?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_canopi_design_schema;

    #[test]
    fn generated_canopi_schema_matches_the_file_authority() {
        let schema = common_types::design::canopi_file_json_schema();
        validate_canopi_design_schema(&schema).expect("Canopi schema should be consumable by Web");
    }

    #[test]
    fn generated_canopi_schema_rejects_decoder_keywords_before_emitting() {
        let mut schema = common_types::design::canopi_file_json_schema();
        schema
            .as_object_mut()
            .expect("root schema object")
            .insert("maxItems".to_owned(), serde_json::json!(1));

        let error = validate_canopi_design_schema(&schema)
            .expect_err("unknown decoder keyword should stop generation");
        assert!(error.to_string().contains("maxItems"));
    }

    #[test]
    fn generated_canopi_schema_rejects_unsupported_numeric_formats() {
        let mut schema = common_types::design::canopi_file_json_schema();
        schema["properties"]["version"]["format"] = serde_json::json!("uint64");

        let error = validate_canopi_design_schema(&schema)
            .expect_err("unknown numeric format should stop generation");
        assert!(error.to_string().contains("uint64"));
    }
}
