use serde::Deserialize;
use std::collections::{BTreeMap, HashMap, HashSet};
use specta::TypeCollection;
use specta_typescript::{BigIntExportBehavior, SerdeMode, Typescript};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let types = TypeCollection::default()
        .register::<common_types::content::DbStatus>()
        .register::<common_types::content::Topic>()
        .register::<common_types::design::Annotation>()
        .register::<common_types::design::AutosaveEntry>()
        .register::<common_types::design::BudgetItem>()
        .register::<common_types::design::CanopiFile>()
        .register::<common_types::design::Consortium>()
        .register::<common_types::design::DesignSummary>()
        .register::<common_types::design::Layer>()
        .register::<common_types::design::Location>()
        .register::<common_types::design::ObjectGroup>()
        .register::<common_types::design::PanelTarget>()
        .register::<common_types::design::PlacedPlant>()
        .register::<common_types::design::Position>()
        .register::<common_types::design::SpeciesPanelTarget>()
        .register::<common_types::design::SpeciesPanelTargetKind>()
        .register::<common_types::design::TimelineAction>()
        .register::<common_types::design::Zone>()
        .register::<common_types::health::PlantDbStatus>()
        .register::<common_types::health::SubsystemHealth>()
        .register::<common_types::settings::Locale>()
        .register::<common_types::settings::Settings>()
        .register::<common_types::settings::Theme>()
        .register::<common_types::species::CommonNameEntry>()
        .register::<common_types::species::DynamicFilter>()
        .register::<common_types::species::DynamicFilterOptions>()
        .register::<common_types::species::FilterOp>()
        .register::<common_types::species::FilterOptions>()
        .register::<common_types::species::FilterValue>()
        .register::<common_types::species::FlowerColorResolution>()
        .register::<common_types::species::PaginatedResult<common_types::species::SpeciesListItem>>()
        .register::<common_types::species::Relationship>()
        .register::<common_types::species::Sort>()
        .register::<common_types::species::SpeciesDetail>()
        .register::<common_types::species::SpeciesExternalLink>()
        .register::<common_types::species::SpeciesFilter>()
        .register::<common_types::species::SpeciesImage>()
        .register::<common_types::species::SpeciesListItem>()
        .register::<common_types::species::SpeciesUse>();

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = root
        .join("../desktop/web/src/generated/contracts.ts");
    let keys_output = root
        .join("../desktop/web/src/generated/known-canopi-keys.ts");
    let plant_filter_schema = root.join("../common-types/plant-filter-fields.json");
    let plant_filter_ts_output = root.join("../desktop/web/src/generated/plant-filter-fields.ts");
    let plant_filter_rust_output = root.join("../desktop/src/db/plant_filter_fields.rs");

    Typescript::default()
        .header("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.")
        .bigint(BigIntExportBehavior::String)
        .with_serde(SerdeMode::Serialize)
        .export_to(&output, &types)?;

    write_known_canopi_keys(&keys_output)?;
    write_plant_filter_adapters(
        &plant_filter_schema,
        &plant_filter_ts_output,
        &plant_filter_rust_output,
    )?;

    Ok(())
}

fn write_known_canopi_keys(path: &PathBuf) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = String::from(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n",
    );
    file.push_str("export const KNOWN_CANOPI_KEYS = [\n");
    for key in [
        "version",
        "name",
        "description",
        "location",
        "north_bearing_deg",
        "plant_species_colors",
        "layers",
        "plants",
        "zones",
        "annotations",
        "consortiums",
        "groups",
        "timeline",
        "budget",
        "budget_currency",
        "created_at",
        "updated_at",
        "extra",
    ] {
        let _ = writeln!(file, "  {key:?},");
    }
    file.push_str("] as const\n");

    std::fs::write(path, file)?;
    Ok(())
}

#[derive(Debug, Deserialize)]
struct PlantFilterSchema {
    version: u32,
    categories: Vec<PlantFilterCategorySchema>,
    orderings: BTreeMap<String, Vec<String>>,
    fields: Vec<PlantFilterFieldSchema>,
}

#[derive(Debug, Deserialize)]
struct PlantFilterCategorySchema {
    key: String,
    i18n_key: String,
    color_token: String,
}

#[derive(Debug, Deserialize)]
struct PlantFilterFieldSchema {
    key: String,
    kind: PlantFilterFieldKind,
    category: String,
    i18n_key: String,
    ui_placement: PlantFilterUiPlacement,
    sql_column: Option<String>,
    step: Option<f64>,
    ordering: Option<String>,
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum PlantFilterFieldKind {
    Boolean,
    Categorical,
    Numeric,
}

impl PlantFilterFieldKind {
    fn ts_value(self) -> &'static str {
        match self {
            Self::Boolean => "boolean",
            Self::Categorical => "categorical",
            Self::Numeric => "numeric",
        }
    }

    fn rust_variant(self) -> &'static str {
        match self {
            Self::Boolean => "PlantFilterFieldKind::Boolean",
            Self::Categorical => "PlantFilterFieldKind::Categorical",
            Self::Numeric => "PlantFilterFieldKind::Numeric",
        }
    }
}

#[derive(Debug, Clone, Copy, Deserialize)]
#[serde(rename_all = "snake_case")]
enum PlantFilterUiPlacement {
    Dynamic,
    Hidden,
    Strip,
}

impl PlantFilterUiPlacement {
    fn ts_value(self) -> &'static str {
        match self {
            Self::Dynamic => "dynamic",
            Self::Hidden => "hidden",
            Self::Strip => "strip",
        }
    }
}

fn write_plant_filter_adapters(
    schema_path: &Path,
    ts_output: &Path,
    rust_output: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let schema = load_plant_filter_schema(schema_path)?;
    write_plant_filter_ts(ts_output, &schema)?;
    write_plant_filter_rust(rust_output, &schema)?;
    Ok(())
}

fn load_plant_filter_schema(
    path: &Path,
) -> Result<PlantFilterSchema, Box<dyn std::error::Error>> {
    let content = std::fs::read_to_string(path)?;
    let schema: PlantFilterSchema = serde_json::from_str(&content)?;
    validate_plant_filter_schema(&schema)?;
    Ok(schema)
}

fn validate_plant_filter_schema(
    schema: &PlantFilterSchema,
) -> Result<(), Box<dyn std::error::Error>> {
    if schema.version != 1 {
        return Err(format!("unsupported plant filter schema version {}", schema.version).into());
    }

    let mut category_keys = HashSet::new();
    for category in &schema.categories {
        if !category_keys.insert(category.key.as_str()) {
            return Err(format!("duplicate plant filter category '{}'", category.key).into());
        }
        if !category.color_token.starts_with("--") {
            return Err(format!(
                "plant filter category '{}' has invalid color token '{}'",
                category.key, category.color_token
            )
            .into());
        }
    }

    let mut field_keys = HashSet::new();
    let mut sql_columns = HashSet::new();
    for field in &schema.fields {
        if !field_keys.insert(field.key.as_str()) {
            return Err(format!("duplicate plant filter field '{}'", field.key).into());
        }
        if !category_keys.contains(field.category.as_str()) {
            return Err(format!(
                "plant filter field '{}' references unknown category '{}'",
                field.key, field.category
            )
            .into());
        }
        if let Some(ordering) = &field.ordering
            && !schema.orderings.contains_key(ordering)
        {
            return Err(format!(
                "plant filter field '{}' references unknown ordering '{}'",
                field.key, ordering
            )
            .into());
        }
        if let PlantFilterUiPlacement::Dynamic = field.ui_placement
            && field.sql_column.is_none()
        {
            return Err(format!(
                "dynamic plant filter field '{}' must declare a SQL column",
                field.key
            )
            .into());
        }
        if let Some(column) = &field.sql_column {
            if !column.starts_with("s.") {
                return Err(format!(
                    "plant filter field '{}' uses non-species SQL column '{}'",
                    field.key, column
                )
                .into());
            }
            if !sql_columns.insert(column.as_str()) {
                return Err(format!("duplicate plant filter SQL column '{}'", column).into());
            }
        }
    }

    Ok(())
}

fn write_plant_filter_ts(
    path: &Path,
    schema: &PlantFilterSchema,
) -> Result<(), Box<dyn std::error::Error>> {
    let categories_by_key: HashMap<&str, &PlantFilterCategorySchema> = schema
        .categories
        .iter()
        .map(|category| (category.key.as_str(), category))
        .collect();
    let mut file = String::from(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n",
    );

    file.push_str("export type FilterCategory =\n");
    write_string_union_members(&mut file, schema.categories.iter().map(|category| &category.key))?;
    file.push('\n');

    file.push_str("export type PlantFilterFieldKind =\n");
    write_string_union_members(&mut file, ["boolean", "categorical", "numeric"].iter())?;
    file.push('\n');

    file.push_str("export type PlantFilterUiPlacement =\n");
    write_string_union_members(&mut file, ["strip", "dynamic", "hidden"].iter())?;
    file.push('\n');

    file.push_str(
        "export interface PlantFilterCategory {\n  key: FilterCategory\n  i18nKey: string\n  colorToken: string\n}\n\n",
    );
    file.push_str(
        "export interface PlantFilterFieldDef {\n  key: string\n  kind: PlantFilterFieldKind\n  category: FilterCategory\n  i18nKey: string\n  uiPlacement: PlantFilterUiPlacement\n  colorToken: string\n  step?: number\n  ordering?: string | null\n}\n\n",
    );

    file.push_str("export const FILTER_CATEGORIES = [\n");
    for category in &schema.categories {
        writeln!(
            file,
            "  {{ key: {}, i18nKey: {}, colorToken: {} }},",
            ts_string(&category.key),
            ts_string(&category.i18n_key),
            ts_string(&category.color_token),
        )?;
    }
    file.push_str("] as const satisfies readonly PlantFilterCategory[]\n\n");

    file.push_str("export const PLANT_FILTER_FIELDS = [\n");
    for field in &schema.fields {
        let color_token = &categories_by_key
            .get(field.category.as_str())
            .expect("schema validation guarantees category exists")
            .color_token;
        write!(
            file,
            "  {{ key: {}, kind: {}, category: {}, i18nKey: {}, uiPlacement: {}, colorToken: {}",
            ts_string(&field.key),
            ts_string(field.kind.ts_value()),
            ts_string(&field.category),
            ts_string(&field.i18n_key),
            ts_string(field.ui_placement.ts_value()),
            ts_string(color_token),
        )?;
        if let Some(step) = field.step {
            write!(file, ", step: {}", format_number(step))?;
        }
        if let Some(ordering) = &field.ordering {
            write!(file, ", ordering: {}", ts_string(ordering))?;
        }
        file.push_str(" },\n");
    }
    file.push_str("] as const satisfies readonly PlantFilterFieldDef[]\n\n");

    file.push_str("export const PLANT_FILTER_SQL_FIELD_KEYS = [\n");
    for field in schema.fields.iter().filter(|field| field.sql_column.is_some()) {
        writeln!(file, "  {},", ts_string(&field.key))?;
    }
    file.push_str("] as const\n\n");

    file.push_str("export const FILTER_VALUE_ORDERINGS: Record<string, readonly string[]> = {\n");
    for (key, values) in &schema.orderings {
        writeln!(file, "  {}: [", ts_string(key))?;
        for value in values {
            writeln!(file, "    {},", ts_string(value))?;
        }
        file.push_str("  ],\n");
    }
    file.push_str("}\n\n");

    file.push_str(
        "const _fieldByKey: ReadonlyMap<string, PlantFilterFieldDef> = new Map(\n  PLANT_FILTER_FIELDS.map((field) => [field.key, field] as const),\n)\n\n",
    );
    file.push_str(
        "const _categoryByKey: ReadonlyMap<FilterCategory, PlantFilterCategory> = new Map(\n  FILTER_CATEGORIES.map((category) => [category.key, category] as const),\n)\n\n",
    );
    file.push_str(
        "const _dynamicFieldsByCategory: ReadonlyMap<FilterCategory, readonly PlantFilterFieldDef[]> = new Map(\n  FILTER_CATEGORIES.map((category) => [\n    category.key,\n    PLANT_FILTER_FIELDS.filter((field) => field.category === category.key && field.uiPlacement === 'dynamic'),\n  ] as const),\n)\n\n",
    );
    file.push_str(
        "export function fieldDefForKey(fieldKey: string): PlantFilterFieldDef | undefined {\n  return _fieldByKey.get(fieldKey)\n}\n\n",
    );
    file.push_str(
        "export function dynamicFilterFieldsForCategory(category: FilterCategory): readonly PlantFilterFieldDef[] {\n  return _dynamicFieldsByCategory.get(category) ?? []\n}\n\n",
    );
    file.push_str(
        "export function categoryForField(fieldKey: string): PlantFilterCategory | undefined {\n  const field = fieldDefForKey(fieldKey)\n  return field ? _categoryByKey.get(field.category) : undefined\n}\n\n",
    );
    file.push_str(
        "export function isStripField(fieldKey: string): boolean {\n  return fieldDefForKey(fieldKey)?.uiPlacement === 'strip'\n}\n\n",
    );
    file.push_str(
        "export function orderingForField(fieldKey: string): readonly string[] | undefined {\n  const ordering = fieldDefForKey(fieldKey)?.ordering\n  return ordering ? FILTER_VALUE_ORDERINGS[ordering] : undefined\n}\n",
    );

    std::fs::write(path, file)?;
    Ok(())
}

fn write_plant_filter_rust(
    path: &Path,
    schema: &PlantFilterSchema,
) -> Result<(), Box<dyn std::error::Error>> {
    let sql_fields: Vec<&PlantFilterFieldSchema> = schema
        .fields
        .iter()
        .filter(|field| field.sql_column.is_some())
        .collect();
    let mut file = String::from(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n",
    );
    file.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    file.push_str("pub(crate) enum PlantFilterFieldKind {\n");
    file.push_str("    Boolean,\n    Categorical,\n    Numeric,\n}\n\n");
    file.push_str("#[derive(Debug)]\n");
    file.push_str("pub(crate) struct PlantFilterField {\n");
    file.push_str("    pub key: &'static str,\n");
    file.push_str("    pub column: &'static str,\n");
    file.push_str("    pub kind: PlantFilterFieldKind,\n");
    file.push_str("}\n\n");
    file.push_str("pub(crate) const PLANT_FILTER_FIELDS: &[PlantFilterField] = &[\n");
    for field in &sql_fields {
        writeln!(
            file,
            "    PlantFilterField {{ key: {}, column: {}, kind: {} }},",
            rust_string(&field.key),
            rust_string(
                field
                    .sql_column
                    .as_deref()
                    .expect("sql_fields contain SQL columns")
            ),
            field.kind.rust_variant(),
        )?;
    }
    file.push_str("];\n\n");
    file.push_str(
        "pub(crate) fn filter_field(key: &str) -> Option<&'static PlantFilterField> {\n    match key {\n",
    );
    for (index, field) in sql_fields.iter().enumerate() {
        writeln!(
            file,
            "        {} => Some(&PLANT_FILTER_FIELDS[{index}]),",
            rust_string(&field.key),
        )?;
    }
    file.push_str("        _ => None,\n    }\n}\n\n");
    file.push_str(
        "pub(crate) fn validated_column(key: &str) -> Option<&'static str> {\n    filter_field(key).map(|field| {\n        debug_assert_eq!(field.key, key);\n        field.column\n    })\n}\n\n",
    );
    file.push_str(
        "pub(crate) fn filter_field_kind(key: &str) -> Option<PlantFilterFieldKind> {\n    filter_field(key).map(|field| field.kind)\n}\n\n",
    );
    file.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");
    file.push_str(
        "    #[test]\n    fn validates_known_columns_and_rejects_unknown_fields() {\n        assert_eq!(validated_column(\"height_max_m\"), Some(\"s.height_max_m\"));\n        assert_eq!(validated_column(\"climate_zones\"), None);\n        assert_eq!(validated_column(\"height_max_m; DROP TABLE species\"), None);\n    }\n\n",
    );
    file.push_str(
        "    #[test]\n    fn exposes_field_kinds_from_schema() {\n        assert_eq!(filter_field_kind(\"woody\"), Some(PlantFilterFieldKind::Boolean));\n        assert_eq!(filter_field_kind(\"growth_form_type\"), Some(PlantFilterFieldKind::Categorical));\n        assert_eq!(filter_field_kind(\"height_max_m\"), Some(PlantFilterFieldKind::Numeric));\n        assert_eq!(filter_field_kind(\"not_a_field\"), None);\n    }\n\n",
    );
    file.push_str(
        "    #[test]\n    fn generated_fields_keep_static_sql_allowlist_entries() {\n        assert!(PLANT_FILTER_FIELDS.iter().all(|field| field.column.starts_with(\"s.\")));\n        assert!(PLANT_FILTER_FIELDS.iter().any(|field| field.key == \"habit\"));\n    }\n",
    );
    file.push_str("}\n");

    std::fs::write(path, file)?;
    Ok(())
}

fn write_string_union_members<I, S>(
    file: &mut String,
    values: I,
) -> Result<(), std::fmt::Error>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    for value in values {
        writeln!(file, "  | {}", ts_string(value.as_ref()))?;
    }
    Ok(())
}

fn ts_string(value: &str) -> String {
    serde_json::to_string(value).expect("serialize TS string literal")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn format_number(value: f64) -> String {
    if value.fract() == 0.0 {
        format!("{}", value as i64)
    } else {
        value.to_string()
    }
}
