use specta::TypeCollection;
use specta_typescript::{BigIntExportBehavior, SerdeMode, Typescript};
use std::fmt::Write as _;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let types = TypeCollection::default()
        .register::<common_types::content::DbStatus>()
        .register::<common_types::content::Topic>()
        .register::<common_types::design::Annotation>()
        .register::<common_types::design::AutosaveEntry>()
        .register::<common_types::design::BudgetItem>()
        .register::<common_types::design::CanopiFile>()
        .register::<common_types::design::Consortium>()
        .register::<common_types::design::DesignSummary>()
        .register::<common_types::design::Layer>()
        .register::<common_types::design::Location>()
        .register::<common_types::design::ObjectGroup>()
        .register::<common_types::design::PanelTarget>()
        .register::<common_types::design::PlacedPlant>()
        .register::<common_types::design::Position>()
        .register::<common_types::design::SpeciesPanelTarget>()
        .register::<common_types::design::SpeciesPanelTargetKind>()
        .register::<common_types::design::TimelineAction>()
        .register::<common_types::design::Zone>()
        .register::<common_types::health::PlantDbStatus>()
        .register::<common_types::health::SubsystemHealth>()
        .register::<common_types::settings::Locale>()
        .register::<common_types::settings::Settings>()
        .register::<common_types::settings::Theme>()
        .register::<common_types::settings::UpdateChannel>()
        .register::<common_types::species::CommonNameEntry>()
        .register::<common_types::species::DynamicFilter>()
        .register::<common_types::species::DynamicFilterOptions>()
        .register::<common_types::species::FilterOp>()
        .register::<common_types::species::FilterOptions>()
        .register::<common_types::species::FilterValue>()
        .register::<common_types::species::FlowerColorResolution>()
        .register::<common_types::species::PaginatedResult<common_types::species::SpeciesListItem>>()
        .register::<common_types::species::Relationship>()
        .register::<common_types::species::Sort>()
        .register::<common_types::species::SpeciesDetail>()
        .register::<common_types::species::SpeciesExternalLink>()
        .register::<common_types::species::SpeciesFilter>()
        .register::<common_types::species::SpeciesImage>()
        .register::<common_types::species::SpeciesListItem>()
        .register::<common_types::species::SpeciesUse>();

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output = root
        .join("../desktop/web/src/generated/contracts.ts");
    let keys_output = root
        .join("../desktop/web/src/generated/known-canopi-keys.ts");

    Typescript::default()
        .header("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.")
        .bigint(BigIntExportBehavior::String)
        .with_serde(SerdeMode::Serialize)
        .export_to(&output, &types)?;

    write_known_canopi_keys(&keys_output)?;

    Ok(())
}

fn write_known_canopi_keys(path: &PathBuf) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = String::from(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n",
    );
    file.push_str("export const KNOWN_CANOPI_KEYS = [\n");
    for key in [
        "version",
        "name",
        "description",
        "location",
        "north_bearing_deg",
        "plant_species_colors",
        "layers",
        "plants",
        "zones",
        "annotations",
        "consortiums",
        "groups",
        "timeline",
        "budget",
        "budget_currency",
        "created_at",
        "updated_at",
        "extra",
    ] {
        let _ = writeln!(file, "  {key:?},");
    }
    file.push_str("] as const\n");

    std::fs::write(path, file)?;
    Ok(())
}
