use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::Path;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct NewDesignDefaults {
    contract_version: u32,
    layers: Vec<NewDesignLayerDefaults>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct NewDesignLayerDefaults {
    name: String,
    visible: bool,
    locked: bool,
    opacity: f32,
}

pub(crate) struct NewDesignDefaultArtifacts {
    pub(crate) typescript: String,
    pub(crate) rust: String,
}

pub(crate) fn render_new_design_defaults(
    path: &Path,
) -> Result<NewDesignDefaultArtifacts, Box<dyn std::error::Error>> {
    let source = std::fs::read_to_string(path)?;
    let value = serde_json::from_str(&source)?;
    let defaults = parse_new_design_defaults_value(value)?;
    Ok(NewDesignDefaultArtifacts {
        typescript: render_typescript(&defaults)?,
        rust: render_rust(&defaults)?,
    })
}

fn parse_new_design_defaults_value(
    value: serde_json::Value,
) -> Result<NewDesignDefaults, Box<dyn std::error::Error>> {
    let object = value
        .as_object()
        .ok_or("New Design defaults must be an object")?;
    for required in ["contract_version", "layers"] {
        if !object.contains_key(required) {
            return Err(
                format!("New Design defaults are missing required field '{required}'").into(),
            );
        }
    }

    let defaults: NewDesignDefaults = serde_json::from_value(value)?;
    if defaults.contract_version != 1 {
        return Err(format!(
            "unsupported New Design defaults contract_version {}",
            defaults.contract_version
        )
        .into());
    }
    if defaults.layers.is_empty() {
        return Err("New Design defaults must declare at least one layer".into());
    }

    let mut names = HashSet::new();
    for (index, layer) in defaults.layers.iter().enumerate() {
        if layer.name.is_empty() || layer.name.trim() != layer.name {
            return Err(format!(
                "New Design layer at index {index} must have a non-empty, trimmed name"
            )
            .into());
        }
        if !names.insert(layer.name.as_str()) {
            return Err(format!("duplicate New Design layer '{}'", layer.name).into());
        }
        if !layer.opacity.is_finite() || !(0.0..=1.0).contains(&layer.opacity) {
            return Err(format!(
                "New Design layer '{}' opacity must be in [0, 1]",
                layer.name
            )
            .into());
        }
    }
    Ok(defaults)
}

fn render_typescript(defaults: &NewDesignDefaults) -> Result<String, Box<dyn std::error::Error>> {
    let layers = serde_json::to_string_pretty(&defaults.layers)?;
    Ok(format!(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n\
         import type {{ Layer }} from './contracts'\n\n\
         export const NEW_DESIGN_LAYER_DEFAULTS = {layers} as const satisfies readonly Layer[]\n"
    ))
}

fn render_rust(defaults: &NewDesignDefaults) -> Result<String, Box<dyn std::error::Error>> {
    let mut file =
        String::from("// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n");
    file.push_str("#[derive(Debug, Clone, Copy, PartialEq)]\n");
    file.push_str("pub(crate) struct NewDesignLayerDefaults {\n");
    file.push_str("    pub(crate) name: &'static str,\n");
    file.push_str("    pub(crate) visible: bool,\n");
    file.push_str("    pub(crate) locked: bool,\n");
    file.push_str("    pub(crate) opacity: f32,\n");
    file.push_str("}\n\n");
    file.push_str("pub(crate) const NEW_DESIGN_LAYER_DEFAULTS: &[NewDesignLayerDefaults] = &[\n");
    for layer in &defaults.layers {
        writeln!(
            file,
            "    NewDesignLayerDefaults {{\n        name: {:?},\n        visible: {},\n        locked: {},\n        opacity: {:?}_f32,\n    }},",
            layer.name, layer.visible, layer.locked, layer.opacity,
        )?;
    }
    file.push_str("];\n");
    Ok(file)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn authored_contract() -> serde_json::Value {
        serde_json::from_str(include_str!(
            "../../common-types/canopi-new-design-defaults.json"
        ))
        .expect("authored New Design defaults should parse as JSON")
    }

    #[test]
    fn rejects_duplicate_layer_names() {
        let mut contract = authored_contract();
        contract["layers"][1]["name"] = contract["layers"][0]["name"].clone();

        let error = parse_new_design_defaults_value(contract)
            .expect_err("duplicate layer identities should stop generation");

        assert!(error.to_string().contains("duplicate New Design layer"));
    }

    #[test]
    fn rejects_out_of_range_layer_opacity() {
        let mut contract = authored_contract();
        contract["layers"][0]["opacity"] = serde_json::json!(1.1);

        let error = parse_new_design_defaults_value(contract)
            .expect_err("invalid layer opacity should stop generation");

        assert!(error.to_string().contains("opacity"));
    }

    #[test]
    fn rejects_obsolete_spatial_frame() {
        let mut contract = authored_contract();
        contract["spatial_frame"] = serde_json::json!({});

        let error = parse_new_design_defaults_value(contract)
            .expect_err("a Design-level spatial frame no longer exists");

        assert!(error.to_string().contains("spatial_frame"));
    }

    #[test]
    fn rejects_unknown_authored_fields() {
        let mut contract = authored_contract();
        contract["layers"][0]["visibile"] = serde_json::json!(true);

        let error = parse_new_design_defaults_value(contract)
            .expect_err("unknown authored fields should stop generation");

        assert!(error.to_string().contains("visibile"));
    }

    #[test]
    fn renders_typed_facts_for_both_consumers() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("common-types/canopi-new-design-defaults.json");

        let artifacts = render_new_design_defaults(&path).expect("authored defaults should render");

        assert!(artifacts.typescript.contains("satisfies readonly Layer[]"));
        assert!(
            artifacts
                .rust
                .contains("pub(crate) const NEW_DESIGN_LAYER_DEFAULTS")
        );
        assert!(artifacts.typescript.contains("measurement-guides"));
        assert!(artifacts.rust.contains("measurement-guides"));
    }
}
