pub(crate) fn render_settings_runtime() -> Result<String, Box<dyn std::error::Error>> {
    let default_settings =
        serde_json::to_string_pretty(&common_types::settings::Settings::default())?;
    let locales = serde_json::to_string_pretty(common_types::settings::Locale::ALL)?;
    let themes = serde_json::to_string_pretty(common_types::settings::Theme::ALL)?;
    let basemap_styles = serde_json::to_string_pretty(common_types::settings::BasemapStyle::ALL)?;
    Ok(format!(
        "// Generated by `cargo run -p bindings-gen`. Do not edit by hand.\n\n\
         import type {{ BasemapStyle, Locale, Settings, Theme }} from './contracts'\n\n\
         export const DEFAULT_SETTINGS = {default_settings} as const satisfies Settings\n\n\
         export const SETTINGS_LOCALES = {locales} as const satisfies readonly Locale[]\n\n\
         export const SETTINGS_THEMES = {themes} as const satisfies readonly Theme[]\n\n\
         export const SETTINGS_BASEMAP_STYLES = {basemap_styles} as const satisfies readonly BasemapStyle[]\n"
    ))
}
