use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::Path;

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct NormalizationContract {
    contract_format_version: u32,
    normalization_version: u32,
    algorithm: NormalizationAlgorithm,
    corpus: Vec<CorpusCase>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct NormalizationAlgorithm {
    compatibility_decomposition: String,
    stripped_general_categories: Vec<String>,
    token_character_classes: Vec<String>,
    case_folds: Vec<CaseFold>,
    minimum_admitted_scalar_count: u32,
    query_token_policy: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CaseFold {
    from: String,
    to: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CorpusCase {
    name: String,
    input: String,
    normalized_text: String,
    tokens: Vec<String>,
    query_tokens: Vec<String>,
    admission: String,
}

pub(crate) fn render_typescript_adapter(
    authority_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let source = std::fs::read_to_string(authority_path)?;
    let raw: serde_json::Value = serde_json::from_str(&source)?;
    let contract: NormalizationContract = serde_json::from_value(raw.clone())?;
    validate(&contract)?;

    let canonical = serde_json::to_vec(&raw)?;
    let fingerprint = format!("{:x}", Sha256::digest(canonical));
    Ok(render_typescript(&contract, &fingerprint)?)
}

fn validate(contract: &NormalizationContract) -> Result<(), Box<dyn std::error::Error>> {
    if contract.contract_format_version != 1 {
        return Err(format!(
            "unsupported Species Search normalization contract format {}",
            contract.contract_format_version
        )
        .into());
    }
    if contract.normalization_version == 0 {
        return Err("Species Search normalization version must be positive".into());
    }
    let algorithm = &contract.algorithm;
    if algorithm.compatibility_decomposition != "NFKD" {
        return Err("Species Search normalization decomposition must be NFKD".into());
    }
    if algorithm.stripped_general_categories != ["Mn", "Mc", "Me"] {
        return Err("Species Search normalization stripped categories must be Mn, Mc, Me".into());
    }
    if algorithm.token_character_classes != ["Letter", "Number", "Underscore"] {
        return Err(
            "Species Search normalization token classes must be Letter, Number, Underscore".into(),
        );
    }
    if algorithm.minimum_admitted_scalar_count == 0 {
        return Err("Species Search admission scalar count must be positive".into());
    }
    if algorithm.query_token_policy != "unique-admitted-or-all-when-active" {
        return Err("Species Search query-token policy is unsupported".into());
    }

    let mut fold_sources = HashSet::new();
    for case_fold in &algorithm.case_folds {
        if case_fold.from.is_empty() || case_fold.to.is_empty() {
            return Err("Species Search case folds must contain nonempty text".into());
        }
        if !fold_sources.insert(case_fold.from.as_str()) {
            return Err(format!(
                "duplicate Species Search case-fold source {:?}",
                case_fold.from
            )
            .into());
        }
    }

    let mut corpus_names = HashSet::new();
    for case in &contract.corpus {
        if case.name.is_empty() || !corpus_names.insert(case.name.as_str()) {
            return Err(format!(
                "Species Search corpus case names must be nonempty and unique: {:?}",
                case.name
            )
            .into());
        }
        if !matches!(
            case.admission.as_str(),
            "browse" | "too-short" | "active-text"
        ) {
            return Err(format!(
                "Species Search corpus case {:?} has invalid admission {:?}",
                case.name, case.admission
            )
            .into());
        }
    }
    Ok(())
}

fn render_typescript(
    contract: &NormalizationContract,
    fingerprint: &str,
) -> Result<String, std::fmt::Error> {
    let mut output = String::from(concat!(
        "// Generated by `cd desktop/web && npm run gen:types`.\n",
        "// Do not edit by hand.\n\n",
        "export type SpeciesSearchAdmission = 'browse' | 'too-short' | 'active-text'\n\n",
        "export interface SpeciesSearchNormalizationCorpusCase {\n",
        "  readonly name: string\n",
        "  readonly input: string\n",
        "  readonly normalizedText: string\n",
        "  readonly tokens: readonly string[]\n",
        "  readonly queryTokens: readonly string[]\n",
        "  readonly admission: SpeciesSearchAdmission\n",
        "}\n\n",
    ));
    writeln!(
        output,
        "export const SPECIES_SEARCH_NORMALIZATION_VERSION = {} as const",
        contract.normalization_version
    )?;
    writeln!(
        output,
        "export const SPECIES_SEARCH_NORMALIZATION_FINGERPRINT = {} as const",
        json_string(fingerprint)
    )?;
    writeln!(
        output,
        "export const SPECIES_SEARCH_MINIMUM_ADMITTED_SCALAR_COUNT = {} as const\n",
        contract.algorithm.minimum_admitted_scalar_count
    )?;
    writeln!(
        output,
        "export const SPECIES_SEARCH_QUERY_TOKEN_POLICY = {} as const\n",
        json_string(&contract.algorithm.query_token_policy)
    )?;

    output.push_str("export const SPECIES_SEARCH_CASE_FOLDS = [\n");
    for case_fold in &contract.algorithm.case_folds {
        writeln!(
            output,
            "  {{ from: {}, to: {} }},",
            json_string(&case_fold.from),
            json_string(&case_fold.to),
        )?;
    }
    output.push_str("] as const\n\n");

    output.push_str("export const SPECIES_SEARCH_NORMALIZATION_CORPUS = [\n");
    for case in &contract.corpus {
        writeln!(output, "  {{")?;
        writeln!(output, "    name: {},", json_string(&case.name))?;
        writeln!(output, "    input: {},", json_string(&case.input))?;
        writeln!(
            output,
            "    normalizedText: {},",
            json_string(&case.normalized_text)
        )?;
        writeln!(output, "    tokens: {},", render_string_array(&case.tokens))?;
        writeln!(
            output,
            "    queryTokens: {},",
            render_string_array(&case.query_tokens)
        )?;
        writeln!(output, "    admission: {},", json_string(&case.admission))?;
        writeln!(output, "  }},")?;
    }
    output.push_str("] as const satisfies readonly SpeciesSearchNormalizationCorpusCase[]\n");
    Ok(output)
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("strings serialize")
}

fn render_string_array(values: &[String]) -> String {
    format!(
        "[{}]",
        values
            .iter()
            .map(|value| json_string(value))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn authored_normalization_contract_renders_versioned_typescript_facts() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let rendered =
            render_typescript_adapter(&root.join("common-types/species-search-normalization.json"))
                .unwrap();

        assert!(rendered.contains("SPECIES_SEARCH_NORMALIZATION_VERSION = 1"));
        assert!(rendered.contains("greek-final-sigma"));
        assert!(rendered.contains("σισυφοσ"));
    }
}
