import type { SpeciesDetail, SpeciesListItem } from '../src/types/species'
import type { CanopiFile } from '../src/types/design'
import { createDefaultScenePersistedState } from '../src/canvas/runtime/scene'
import { serializeScenePersistedState } from '../src/canvas/runtime/scene'

export const detail: SpeciesDetail = {
  "canonical_name": "Malus domestica",
  "common_name": "Apple",
  "family": "Rosaceae",
  "genus": null,
  "taxonomic_order": null,
  "taxonomic_class": null,
  "is_hybrid": null,
  "match_confidence": null,
  "tnrs_taxonomic_status": null,
  "match_score": null,
  "enriched_at": null,
  "height_min_m": null,
  "height_max_m": 8,
  "width_max_m": 6,
  "hardiness_zone_min": null,
  "hardiness_zone_max": null,
  "age_of_maturity_years": null,
  "growth_rate": null,
  "is_annual": null,
  "is_biennial": null,
  "is_perennial": true,
  "lifespan": null,
  "deciduous_evergreen": null,
  "leaf_retention": null,
  "active_growth_period": null,
  "habit": null,
  "growth_form_type": null,
  "growth_form_shape": null,
  "growth_habit": null,
  "woody": null,
  "canopy_position": null,
  "resprout_ability": null,
  "coppice_potential": null,
  "bloom_period": null,
  "flower_color": "white",
  "pollinators": null,
  "tolerates_full_sun": null,
  "tolerates_semi_shade": null,
  "tolerates_full_shade": null,
  "frost_tender": null,
  "frost_free_days_min": null,
  "drought_tolerance": null,
  "precip_min_inches": null,
  "precip_max_inches": null,
  "soil_ph_min": null,
  "soil_ph_max": null,
  "well_drained": null,
  "heavy_clay": null,
  "tolerates_light_soil": null,
  "tolerates_medium_soil": null,
  "tolerates_heavy_soil": null,
  "tolerates_acid": null,
  "tolerates_alkaline": null,
  "tolerates_saline": null,
  "tolerates_wind": null,
  "tolerates_pollution": null,
  "tolerates_nutritionally_poor": null,
  "fertility_requirement": null,
  "moisture_use": null,
  "anaerobic_tolerance": null,
  "root_depth_min_cm": null,
  "salinity_tolerance": null,
  "stratum": "high",
  "succession_stage": null,
  "stratum_confidence": null,
  "succession_confidence": null,
  "nitrogen_fixer": null,
  "ecological_system": null,
  "mycorrhizal_type": null,
  "grime_strategy": null,
  "raunkiaer_life_form": null,
  "cn_ratio": null,
  "allelopathic": null,
  "root_system_type": null,
  "taproot_persistent": null,
  "edibility_rating": 5,
  "medicinal_rating": null,
  "other_uses_rating": null,
  "attracts_wildlife": null,
  "scented": null,
  "uses": [],
  "propagated_by_seed": null,
  "propagated_by_cuttings": null,
  "propagated_by_bare_root": null,
  "propagated_by_container": null,
  "propagated_by_sprigs": null,
  "propagated_by_bulb": null,
  "propagated_by_sod": null,
  "propagated_by_tubers": null,
  "propagated_by_corm": null,
  "cold_stratification_required": null,
  "vegetative_spread_rate": null,
  "seed_spread_rate": null,
  "propagation_method": null,
  "sowing_period": null,
  "harvest_period": null,
  "dormancy_conditions": null,
  "management_types": null,
  "fruit_type": null,
  "fruit_seed_color": null,
  "fruit_seed_period_begin": null,
  "fruit_seed_period_end": null,
  "fruit_seed_abundance": null,
  "fruit_seed_persistence": null,
  "seed_mass_mg": null,
  "seed_length_mm": null,
  "seed_germination_rate": null,
  "seed_dispersal_mechanism": null,
  "seed_storage_behaviour": null,
  "seed_dormancy_type": null,
  "seed_dormancy_depth": null,
  "serotinous": null,
  "seedbank_type": null,
  "leaf_type": null,
  "leaf_compoundness": null,
  "leaf_shape": null,
  "sla_mm2_mg": null,
  "ldmc_g_g": null,
  "leaf_nitrogen_mg_g": null,
  "leaf_carbon_mg_g": null,
  "leaf_phosphorus_mg_g": null,
  "leaf_dry_mass_mg": null,
  "pollination_syndrome": null,
  "sexual_system": null,
  "mating_system": null,
  "self_fertile": null,
  "reproductive_type": null,
  "clonal_growth_form": null,
  "storage_organ": null,
  "toxicity": null,
  "invasive_potential": null,
  "biogeographic_status": null,
  "noxious_status": null,
  "invasive_usda": null,
  "weed_potential": null,
  "fire_resistant": null,
  "fire_tolerance": null,
  "hedge_tolerance": null,
  "native_distribution": null,
  "introduced_distribution": null,
  "climate_zones": "temperate",
  "conservation_status": null,
  "image_urls": null,
  "ellenberg_light": null,
  "ellenberg_temperature": null,
  "ellenberg_moisture": null,
  "ellenberg_reaction": null,
  "ellenberg_nitrogen": null,
  "ellenberg_salt": null,
  "overall_confidence": null,
  "data_quality_tier": null,
  "wood_density_g_cm3": null,
  "photosynthesis_pathway": null,

}
const baseSpecies: SpeciesListItem = {
  "canonical_name": "Malus domestica",
  "slug": "",
  "common_name": "Apple",
  "common_name_2": null,
  "matched_common_name": null,
  "is_name_fallback": false,
  "family": "Rosaceae",
  "genus": null,
  "height_max_m": 8,
  "hardiness_zone_min": null,
  "hardiness_zone_max": null,
  "growth_rate": null,
  "stratum": "high",
  "climate_zones": [
    "temperate"
  ],
  "life_cycles": [
    "perennial"
  ],
  "edibility_rating": null,
  "medicinal_rating": null,
  "width_max_m": 6,
  "is_favorite": true
}
export const specimens = [
  ['Malus domestica', 'Apple', 'canopy', '#C8A51E'],
  ['Lavandula angustifolia', 'English lavender', 'shrub', '#8856A7'],
  ['Mentha spicata', 'Spearmint', 'herb', '#4E8A57'],
  ['Achillea millefolium', 'Common yarrow', 'herb', '#E9D28B'],
  ['Corylus avellana', 'Hazel', 'shrub', '#A9845A'],
  ['Fragaria vesca', 'Wild strawberry', 'groundcover', '#C44230'],
] as const
export const species: SpeciesListItem[] = specimens.map(([canonical_name, common_name]) => ({ ...baseSpecies, canonical_name, common_name }))
export function designFixture(state = 'populated'): CanopiFile {
  const scene = createDefaultScenePersistedState()
  const plants = state === 'empty' ? [] : specimens.flatMap(([canonicalName, commonName], speciesIndex) =>
    Array.from({ length: speciesIndex === 0 ? 3 : 8 }, (_, i) => ({
      kind: 'plant' as const, id: `plant-${speciesIndex}-${i}`, canonicalName,
      commonName: state === 'long' ? `${commonName} — a particularly long local cultivar name` : commonName,
      position: { x: speciesIndex * 3 + (i % 3) * .7, y: (i % 4) * 2 + (speciesIndex % 2) },
      color: state === 'mixed' && i === 0 ? '#C44230' : specimens[speciesIndex]![3], symbol: state === 'mixed' && i === 0 ? 'conifer' : null,
      stratum: null, canopySpreadM: speciesIndex === 0 ? 2 : .7, rotationDeg: null, scale: speciesIndex === 0 ? 2 : .7,
      notes: null, plantedDate: null, quantity: null, locked: false,
    })))
  if (state === 'dense') plants.forEach((plant, index) => {
    plant.position = { x: (index % 7) * .32, y: Math.floor(index / 7) * .36 }
  })
  return {
    ...serializeScenePersistedState({ ...scene, plants,
      plantSpeciesColors: Object.fromEntries(specimens.map(([name, , , color]) => [name, color])),
      plantSpeciesSymbols: Object.fromEntries(specimens.map(([name, , symbol]) => [name, symbol])),
    }, { now: new Date('2026-01-01T00:00:00Z') }),
    name: 'Orchard notebook',
    location: state === 'located' ? { lat: 48.85, lon: 2.35, altitude_m: 35 } : null,
  }
}
