#!/usr/bin/env bash
# Writes desktop/src/services/lidar/rust_engine/crs_reference_points.rs: PROJ's
# coordinates of one point per code, which the raster engine's CRS tests must
# match: 1 cm; 8 m for Krovak (5514, 5513, 2065), whose PROJ method differs
# from proj4rs; 0.5 m for Martinique 2973, whose definition carries EPSG's 10 m Helmert shift
# where PROJ takes the 0.1 m one. The engine's own inverse closes within 1e-8
# deg, 3e-8 deg (3 mm) for a code with a datum shift, which moves the
# ellipsoidal height a 2-D transform drops.
#
#   scripts/gen_crs_reference_points.sh
#
# Needs cs2cs and projinfo from PROJ 9.4.0. Grids are kept out
# (PROJ_NETWORK=OFF and a PROJ_DATA holding only proj.db), so every datum step
# is the Helmert shift the engine applies, whatever grids the machine has.
# Output axes are put in the order GDAL stores them, from projinfo's axis
# directions: a northing-first grid swapped to easting first, a south-west
# Krovak (5513, 2065) left southing first; values stay in each code's own
# linear unit (US feet for 2263).
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=$ROOT/desktop/src/services/lidar/rust_engine/crs_reference_points.rs

version=$(cs2cs 2>&1 | head -1 | awk '{print $2}' | tr -d ,)
if [ "$version" != "9.4.0" ]; then
  echo "PROJ 9.4.0 expected, found ${version:-none}" >&2
  exit 1
fi
db=""
for dir in $(projinfo --searchpaths); do
  if [ -f "$dir/proj.db" ]; then db=$dir/proj.db; break; fi
done
[ -n "$db" ] || { echo "proj.db not found" >&2; exit 1; }
data=$(mktemp -d)
trap 'rm -rf "$data"' EXIT
ln -s "$db" "$data/proj.db"
export PROJ_DATA=$data PROJ_NETWORK=OFF

# code latitude longitude: a point inside each code's area of use.
points=$(cat <<'P'
2154 48.85 2.35
2056 47.0 8.0
21781 46.2 6.14
3035 48.85 2.35
28992 52.15517440 5.38720621
28992 53.2 6.5
31370 50.85 4.35
27700 51.5 -0.12
27700 57.5 -4.2
5514 50.09 14.42
25832 50.0 9.0
3857 48.0 2.0
3812 50.85 4.35
2180 52.23 21.0
3006 59.33 18.07
2193 -36.85 174.76
26917 43.65 -79.38
2263 40.71 -74.0
3067 60.17 24.94
31287 48.2 16.37
3765 45.8 15.98
25833 52.5 13.4
2100 37.98 23.73
3763 38.72 -9.14
25830 40.4 -3.7
6706 41.9 12.5
3416 48.2 16.37
2169 49.61 6.13
5698 45.76 4.83
2975 -21.1 55.5
27572 48.85 2.35
27571 49.9 2.3
23700 47.5 19.05
2973 14.6 -61.0
3942 42.7 2.9
3949 49.2 2.5
2972 4.9 -52.3
31467 50.0 9.0
2062 40.4 -3.7
5513 49.395 17.325
2065 49.395 17.325
P
)

{
  echo "//! PROJ's coordinates of one point per code, for the CRS tests."
  echo "//!"
  echo "//! Generated by \`scripts/gen_crs_reference_points.sh\` from PROJ $version (cs2cs,"
  echo "//! PROJ_NETWORK=OFF, no grid files); do not edit by hand."
  echo
  echo "/// \`(EPSG code, longitude, latitude, x, y)\`: WGS84 degrees in, the code's"
  echo "/// coordinates out in the order GDAL stores them, in its own linear unit."
  echo "pub(super) const REFERENCE_POINTS: &[(u32, f64, f64, f64, f64)] = &["
  while read -r code lat lon; do
    first=$(projinfo -q -o WKT2_2019 "EPSG:$code" | grep -oE 'AXIS\["[^"]*",(east|north|west|south)' | head -1 | sed 's/.*,//')
    read -r a b _ <<<"$(echo "$lat $lon" | cs2cs -f %.6f EPSG:4326 "EPSG:$code")"
    case "$first" in
      north) x=$b y=$a ;;
      *) x=$a y=$b ;;
    esac
    echo "    ($code, $lon, $lat, $x, $y),"
  done <<<"$points"
  echo "];"
} >|"$OUT"
echo "wrote $OUT"
