#!/usr/bin/env bash
# Writes desktop/src/services/lidar/rust_engine/crs_reference_points.rs: PROJ's
# coordinates of a 3x3 grid of points inside each row's area of use in
# crs_table.rs, which the CRS authority's tests must match.
#
#   scripts/gen_crs_reference_points.sh
#
# Two references per point, both from cs2cs:
#   - from WGS84 longitude and latitude to the row's own PROJ definition, so
#     the same Helmert shift (the authority must match it within 1 cm);
#   - from EPSG:4326 to EPSG:n, so PROJ's own choice of operation (within the
#     row's stated accuracy, at most 10 m).
# Grids are kept out (PROJ_NETWORK=OFF and a PROJ_DATA holding only proj.db),
# so PROJ's choice is a Helmert shift whatever grids the machine has. Output
# axes are put easting first (longitude first for a geographic code), the
# order GeoTIFF stores them, from projinfo's axis directions.
#
# Needs cs2cs and projinfo from PROJ 9.4.0.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TABLE=$ROOT/desktop/src/services/lidar/rust_engine/crs_table.rs
OUT=$ROOT/desktop/src/services/lidar/rust_engine/crs_reference_points.rs

version=$(cs2cs 2>&1 | head -1 | awk '{print $2}' | tr -d ,)
if [ "$version" != "9.4.0" ]; then
  echo "PROJ 9.4.0 expected, found ${version:-none}" >&2
  exit 1
fi
db=""
for dir in $(projinfo --searchpaths); do
  if [ -f "$dir/proj.db" ]; then db=$dir/proj.db; break; fi
done
[ -n "$db" ] || { echo "proj.db not found" >&2; exit 1; }
data=$(mktemp -d)
trap 'rm -rf "$data"' EXIT
ln -s "$db" "$data/proj.db"
export PROJ_DATA=$data PROJ_NETWORK=OFF
WGS84="+proj=longlat +datum=WGS84 +type=crs"

rows=$(sed -nE 's/^ *row\(([0-9]+), "[^"]*", "([^"]*)", \[([^]]*)\], [0-9.]+\),$/\1|\2|\3/p' "$TABLE")
[ -n "$rows" ] || { echo "no rows read from $TABLE" >&2; exit 1; }

# Two columns from one cs2cs call over the "lon lat" points, the input put
# latitude first for EPSG:4326 and the output swapped back when the target's
# first axis is north; "*" fails the script.
project() {
  local points=$1 swap=$2 source=$3
  shift 3
  local input=$points
  [ "$source" = EPSG:4326 ] && input=$(echo "$points" | awk '{ print $2, $1 }')
  echo "$input" | cs2cs -f %.9f $source +to "$@" | awk -v swap="$swap" '
    $1 == "*" || $2 == "*" { exit 1 }
    { if (swap == "1") print $2, $1; else print $1, $2 }'
}

{
  echo "//! PROJ's coordinates of a 3x3 grid of points per row of \`crs_table.rs\`."
  echo "//!"
  echo "//! Generated by \`scripts/gen_crs_reference_points.sh\` from PROJ $version (cs2cs,"
  echo "//! PROJ_NETWORK=OFF, no grid files); do not edit by hand."
  echo
  echo "#![allow(clippy::excessive_precision)] // cs2cs prints nine decimals."
  echo
  echo "/// \`(EPSG code, longitude, latitude, row x, row y, EPSG x, EPSG y)\`: WGS84"
  echo "/// degrees in; out, the row's own definition and PROJ's own operation for the"
  echo "/// code, easting (or longitude) first."
  echo "#[rustfmt::skip]"
  echo "pub(super) const REFERENCE_POINTS: &[(u32, f64, f64, f64, f64, f64, f64)] = &["
  while IFS='|' read -r code proj area; do
    points=$(echo "$area" | awk -F', *' '{
      split("0.1 0.5 0.9", f, " ")
      for (i = 1; i <= 3; i++) for (j = 1; j <= 3; j++)
        printf "%.6f %.6f\n", $1 + ($3 - $1) * f[i], $2 + ($4 - $2) * f[j]
    }')
    first=$(projinfo -q -o WKT2_2019 "EPSG:$code" | grep -oE 'AXIS\["[^"]*",(east|north|west|south)' | head -1 | sed 's/.*,//')
    swap=0
    [ "$first" = north ] && swap=1
    by_row=$(project "$points" 0 "$WGS84" $proj +type=crs) || { echo "cs2cs refused row $code" >&2; exit 1; }
    by_code=$(project "$points" "$swap" EPSG:4326 "EPSG:$code") || { echo "cs2cs refused EPSG:$code" >&2; exit 1; }
    paste -d' ' <(echo "$points") <(echo "$by_row") <(echo "$by_code") |
      awk -v code="$code" '{ printf "    (%s, %s, %s, %s, %s, %s, %s),\n", code, $1, $2, $3, $4, $5, $6 }'
  done <<<"$rows"
  echo "];"
} >|"$OUT"
echo "wrote $OUT"
