// Generated by `cargo run -p bindings-gen`. Do not edit by hand.
// Source: common-types/analysis-registry.json

use common_types::analysis_registry as r;
use common_types::library::{LibraryItemType, RasterQuantity};

/// Every registered analysis, in registry order.
pub(crate) static ANALYSIS_REGISTRY: &[r::AnalysisDefinition] = &[r::AnalysisDefinition {
    id: "terrain.slope",
    version: 1,
    group: r::AnalysisGroup::Terrain,
    lane: r::AnalysisLane::GeolibreWindowed { halo: 2 },
    inputs: &[r::AnalysisInputSpec {
        key: "dem",
        accepts: &[LibraryItemType::Raster {
            quantity: RasterQuantity::GroundElevation,
        }],
        requires: &[
            r::GridRequirement::ProjectedMetreGrid,
            r::GridRequirement::MetreValues,
        ],
    }],
    params: &[r::AnalysisParamSpec {
        key: "unit",
        kind: r::AnalysisParamKind::Choice {
            options: &["degrees", "percent"],
        },
        default: r::ParamDefault::Required,
        advanced: false,
        visible_when: None,
    }],
    outputs: &[r::AnalysisOutputSpec {
        key: "slope",
        item: LibraryItemType::Raster {
            quantity: RasterQuantity::Slope,
        },
        units: r::OutputUnits::ByParam {
            param: "unit",
            map: &[("degrees", "°"), ("percent", "%")],
        },
        optional: false,
        default_selected: true,
        presentable: true,
    }],
}];
