#!/usr/bin/env python3
"""Static server for the qualification browser runner.

Everything the page loads comes from one of three local roots and nothing else:

* ``/runner/``  the harness sources in this directory,
* ``/wb/``, ``/ct/``, ``/nm/``  the installed candidate packages,
* ``/fx/``  the caller-supplied fixture root.

No network origin is reachable, which is what makes the probe a *local*
transport result rather than an HTTP-CDN demo.

Usage::

    python3 scripts/raster-qualification/serve_bench.py \
        --bench <dir> --fixtures <dir> --import-map <json> --port 8799
"""

from __future__ import annotations

import argparse
import http.server
import json
import socketserver
import sys
import tempfile
from pathlib import Path

MODULE_SUFFIXES = (".js", ".mjs", ".json")

# A browser enforces strict MIME checking on module scripts; the stdlib default
# for some of these extensions is application/octet-stream, which would make the
# probe fail for reasons unrelated to the candidate.
CONTENT_TYPES = {
    ".js": "text/javascript",
    ".mjs": "text/javascript",
    ".cjs": "text/javascript",
    ".json": "application/json",
    ".wasm": "application/wasm",
    ".html": "text/html; charset=utf-8",
    ".tif": "image/tiff",
    ".tiff": "image/tiff",
    ".png": "image/png",
}


class QualHandler(http.server.SimpleHTTPRequestHandler):
    """Shared behavior for the qualification static roots."""

    def guess_type(self, path):  # noqa: D102 - stdlib hook
        suffix = Path(str(path)).suffix.lower()
        if suffix in CONTENT_TYPES:
            return CONTENT_TYPES[suffix]
        return super().guess_type(path)


def build_handler(harness: Path, bench: Path, fixtures: Path, import_map: Path):
    payload = json.loads(import_map.read_text())
    runner_html = (harness / "runner.html").read_text().replace(
        "__QUAL_IMPORT_MAP__",
        '<script type="importmap">' + json.dumps(payload, sort_keys=True) + "</script>",
    )
    overlay = Path(tempfile.mkdtemp(prefix="qual-runner-"))
    (overlay / "runner.html").write_text(runner_html)
    # Inert stubs for Node builtins pulled in by a candidate's ESM entry point.
    stub_root = import_map.parent / "stubs"

    class Handler(QualHandler):
        def translate_path(self, path: str) -> str:
            clean = path.split("?", 1)[0].split("#", 1)[0]
            roots = (
                ("/runner/", harness),
                ("/stub/", stub_root),
                ("/wb/", bench / "node_modules" / "whitebox-wasm"),
                ("/ct/", bench / "node_modules" / "cog-tiler-wasm"),
                ("/nm/", bench / "node_modules"),
                ("/fx/", fixtures),
            )
            if clean in ("", "/", "/runner.html"):
                return str(overlay / "runner.html")
            resolved: Path | None = None
            for prefix, root in roots:
                if clean.startswith(prefix):
                    resolved = root / clean[len(prefix):]
                    break
            if resolved is None:
                resolved = overlay / "runner.html"
            if not resolved.is_file():
                # Candidate peers use extensionless relative imports, which a
                # plain static server does not resolve.
                for suffix in MODULE_SUFFIXES:
                    candidate = Path(str(resolved) + suffix)
                    if candidate.is_file():
                        resolved = candidate
                        break
            if not resolved.is_file():
                # Name the specifier that failed so a browser 404 is diagnosable
                # instead of guessed at.
                print(f"MISS {clean} -> {resolved}", file=sys.stderr, flush=True)
            return str(resolved)

        def log_message(self, fmt, *args):
            pass

    return Handler


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--bench", required=True, type=Path,
                        help="directory containing node_modules with the candidate packages")
    parser.add_argument("--fixtures", required=True, type=Path,
                        help="fixture root exposed read-only at /fx/")
    parser.add_argument("--import-map", required=True, type=Path,
                        help="import map generated by import_map.py")
    parser.add_argument("--port", type=int, default=8799)
    args = parser.parse_args()

    harness = Path(__file__).resolve().parent
    bench, fixtures = args.bench.resolve(), args.fixtures.resolve()
    for required in (bench / "node_modules" / "whitebox-wasm" / "whitebox_wasm.js",
                     bench / "node_modules" / "cog-tiler-wasm" / "cog-tiler.js"):
        if not required.is_file():
            print(f"ERROR: missing candidate file {required}", file=sys.stderr)
            return 2
    if not fixtures.is_dir():
        print(f"ERROR: fixture root {fixtures} is not a directory", file=sys.stderr)
        return 2

    handler = build_handler(harness, bench, fixtures, args.import_map.resolve())
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("127.0.0.1", args.port), handler) as httpd:
        print(f"serving on http://127.0.0.1:{args.port}/", flush=True)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
