// Generated by `cargo run -p bindings-gen`. Do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PlantFilterFieldKind {
    Boolean,
    Categorical,
    Numeric,
}

#[derive(Debug)]
pub(crate) struct PlantFilterField {
    pub key: &'static str,
    pub column: &'static str,
    pub kind: PlantFilterFieldKind,
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct FixedFilterBooleanMapping {
    pub value: &'static str,
    pub clause: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub(crate) enum FixedFilterPredicate {
    MappedBooleanList(&'static [FixedFilterBooleanMapping]),
    TextInColumn(&'static str),
    TextEqualsColumn(&'static str),
    BooleanTrueClause(&'static str),
    NumericGteColumn(&'static str),
    ClimateZoneJoin,
    SchemaTextIn { field_key: &'static str },
    SchemaBooleanTrue { field_key: &'static str },
}

#[derive(Debug)]
pub(crate) struct FixedFilterBehavior {
    pub key: &'static str,
    pub predicate: FixedFilterPredicate,
}

#[derive(Debug, Clone, Copy)]
pub(crate) enum FixedFilterValue<'a> {
    StringList(Option<&'a [String]>),
    Boolean(Option<bool>),
    Integer(Option<i32>),
    Text(Option<&'a String>),
}

pub(crate) const PLANT_FILTER_FIELDS: &[PlantFilterField] = &[
    PlantFilterField {
        key: "stratum",
        column: "s.stratum",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "woody",
        column: "s.woody",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "habit",
        column: "s.habit",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "growth_form_type",
        column: "s.growth_form_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "growth_form_shape",
        column: "s.growth_form_shape",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "growth_habit",
        column: "s.growth_habit",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "canopy_position",
        column: "s.canopy_position",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "deciduous_evergreen",
        column: "s.deciduous_evergreen",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "resprout_ability",
        column: "s.resprout_ability",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "coppice_potential",
        column: "s.coppice_potential",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "active_growth_period",
        column: "s.active_growth_period",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "hardiness_zone_min",
        column: "s.hardiness_zone_min",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "hardiness_zone_max",
        column: "s.hardiness_zone_max",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "height_max_m",
        column: "s.height_max_m",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "frost_tender",
        column: "s.frost_tender",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "drought_tolerance",
        column: "s.drought_tolerance",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "soil_ph_min",
        column: "s.soil_ph_min",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "soil_ph_max",
        column: "s.soil_ph_max",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "tolerates_acid",
        column: "s.tolerates_acid",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "tolerates_alkaline",
        column: "s.tolerates_alkaline",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "tolerates_saline",
        column: "s.tolerates_saline",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "tolerates_wind",
        column: "s.tolerates_wind",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "tolerates_pollution",
        column: "s.tolerates_pollution",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "tolerates_nutritionally_poor",
        column: "s.tolerates_nutritionally_poor",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "fertility_requirement",
        column: "s.fertility_requirement",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "moisture_use",
        column: "s.moisture_use",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "anaerobic_tolerance",
        column: "s.anaerobic_tolerance",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "root_depth_min_cm",
        column: "s.root_depth_min_cm",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "frost_free_days_min",
        column: "s.frost_free_days_min",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "precip_min_inches",
        column: "s.precip_min_inches",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "precip_max_inches",
        column: "s.precip_max_inches",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "succession_stage",
        column: "s.succession_stage",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "ecological_system",
        column: "s.ecological_system",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "mycorrhizal_type",
        column: "s.mycorrhizal_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "grime_strategy",
        column: "s.grime_strategy",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "allelopathic",
        column: "s.allelopathic",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "root_system_type",
        column: "s.root_system_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "attracts_wildlife",
        column: "s.attracts_wildlife",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "cn_ratio",
        column: "s.cn_ratio",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "raunkiaer_life_form",
        column: "s.raunkiaer_life_form",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "photosynthesis_pathway",
        column: "s.photosynthesis_pathway",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "ellenberg_light",
        column: "s.ellenberg_light",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "ellenberg_temperature",
        column: "s.ellenberg_temperature",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "ellenberg_moisture",
        column: "s.ellenberg_moisture",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "ellenberg_reaction",
        column: "s.ellenberg_reaction",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "ellenberg_nitrogen",
        column: "s.ellenberg_nitrogen",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "ellenberg_salt",
        column: "s.ellenberg_salt",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "pollination_syndrome",
        column: "s.pollination_syndrome",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "self_fertile",
        column: "s.self_fertile",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "reproductive_type",
        column: "s.reproductive_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "sexual_system",
        column: "s.sexual_system",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "vegetative_spread_rate",
        column: "s.vegetative_spread_rate",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "seed_spread_rate",
        column: "s.seed_spread_rate",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "mating_system",
        column: "s.mating_system",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "clonal_growth_form",
        column: "s.clonal_growth_form",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "storage_organ",
        column: "s.storage_organ",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "bloom_period",
        column: "s.bloom_period",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "flower_color",
        column: "s.flower_color",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "propagated_by_seed",
        column: "s.propagated_by_seed",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "propagated_by_cuttings",
        column: "s.propagated_by_cuttings",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "cold_stratification_required",
        column: "s.cold_stratification_required",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "fruit_type",
        column: "s.fruit_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "seed_dispersal_mechanism",
        column: "s.seed_dispersal_mechanism",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "seed_storage_behaviour",
        column: "s.seed_storage_behaviour",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "fruit_seed_abundance",
        column: "s.fruit_seed_abundance",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "seed_dormancy_type",
        column: "s.seed_dormancy_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "seed_dormancy_depth",
        column: "s.seed_dormancy_depth",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "serotinous",
        column: "s.serotinous",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "leaf_type",
        column: "s.leaf_type",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "leaf_compoundness",
        column: "s.leaf_compoundness",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "leaf_shape",
        column: "s.leaf_shape",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "toxicity",
        column: "s.toxicity",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "invasive_potential",
        column: "s.invasive_potential",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "biogeographic_status",
        column: "s.biogeographic_status",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "noxious_status",
        column: "s.noxious_status",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "invasive_usda",
        column: "s.invasive_usda",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "weed_potential",
        column: "s.weed_potential",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "fire_resistant",
        column: "s.fire_resistant",
        kind: PlantFilterFieldKind::Boolean,
    },
    PlantFilterField {
        key: "fire_tolerance",
        column: "s.fire_tolerance",
        kind: PlantFilterFieldKind::Categorical,
    },
    PlantFilterField {
        key: "medicinal_rating",
        column: "s.medicinal_rating",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "other_uses_rating",
        column: "s.other_uses_rating",
        kind: PlantFilterFieldKind::Numeric,
    },
    PlantFilterField {
        key: "scented",
        column: "s.scented",
        kind: PlantFilterFieldKind::Boolean,
    },
];

const SUN_TOLERANCES_BOOLEAN_MAPPINGS: &[FixedFilterBooleanMapping] = &[
    FixedFilterBooleanMapping {
        value: "full_sun",
        clause: "s.tolerates_full_sun = 1",
    },
    FixedFilterBooleanMapping {
        value: "semi_shade",
        clause: "s.tolerates_semi_shade = 1",
    },
    FixedFilterBooleanMapping {
        value: "full_shade",
        clause: "s.tolerates_full_shade = 1",
    },
];

const SOIL_TOLERANCES_BOOLEAN_MAPPINGS: &[FixedFilterBooleanMapping] = &[
    FixedFilterBooleanMapping {
        value: "light",
        clause: "s.tolerates_light_soil = 1",
    },
    FixedFilterBooleanMapping {
        value: "medium",
        clause: "s.tolerates_medium_soil = 1",
    },
    FixedFilterBooleanMapping {
        value: "heavy",
        clause: "s.tolerates_heavy_soil = 1",
    },
    FixedFilterBooleanMapping {
        value: "well_drained",
        clause: "s.well_drained = 1",
    },
    FixedFilterBooleanMapping {
        value: "heavy_clay",
        clause: "s.heavy_clay = 1",
    },
];

const LIFE_CYCLE_BOOLEAN_MAPPINGS: &[FixedFilterBooleanMapping] = &[
    FixedFilterBooleanMapping {
        value: "Annual",
        clause: "s.is_annual = 1",
    },
    FixedFilterBooleanMapping {
        value: "Biennial",
        clause: "s.is_biennial = 1",
    },
    FixedFilterBooleanMapping {
        value: "Perennial",
        clause: "s.is_perennial = 1",
    },
];

pub(crate) const SPECIES_FILTER_FIXED_BEHAVIORS: &[FixedFilterBehavior] = &[
    FixedFilterBehavior {
        key: "sun_tolerances",
        predicate: FixedFilterPredicate::MappedBooleanList(SUN_TOLERANCES_BOOLEAN_MAPPINGS),
    },
    FixedFilterBehavior {
        key: "soil_tolerances",
        predicate: FixedFilterPredicate::MappedBooleanList(SOIL_TOLERANCES_BOOLEAN_MAPPINGS),
    },
    FixedFilterBehavior {
        key: "life_cycle",
        predicate: FixedFilterPredicate::MappedBooleanList(LIFE_CYCLE_BOOLEAN_MAPPINGS),
    },
    FixedFilterBehavior {
        key: "growth_rate",
        predicate: FixedFilterPredicate::TextInColumn("s.growth_rate"),
    },
    FixedFilterBehavior {
        key: "edible",
        predicate: FixedFilterPredicate::BooleanTrueClause("s.edibility_rating > 0"),
    },
    FixedFilterBehavior {
        key: "edibility_min",
        predicate: FixedFilterPredicate::NumericGteColumn("s.edibility_rating"),
    },
    FixedFilterBehavior {
        key: "nitrogen_fixer",
        predicate: FixedFilterPredicate::BooleanTrueClause("s.nitrogen_fixer = 1"),
    },
    FixedFilterBehavior {
        key: "family",
        predicate: FixedFilterPredicate::TextEqualsColumn("s.family"),
    },
    FixedFilterBehavior {
        key: "climate_zones",
        predicate: FixedFilterPredicate::ClimateZoneJoin,
    },
    FixedFilterBehavior {
        key: "habit",
        predicate: FixedFilterPredicate::SchemaTextIn { field_key: "habit" },
    },
    FixedFilterBehavior {
        key: "woody",
        predicate: FixedFilterPredicate::SchemaBooleanTrue { field_key: "woody" },
    },
];

pub(crate) fn fixed_filter_value<'a>(
    filters: &'a common_types::species::SpeciesFilter,
    key: &str,
) -> Option<FixedFilterValue<'a>> {
    match key {
        "sun_tolerances" => Some(FixedFilterValue::StringList(
            filters.sun_tolerances.as_deref(),
        )),
        "soil_tolerances" => Some(FixedFilterValue::StringList(
            filters.soil_tolerances.as_deref(),
        )),
        "life_cycle" => Some(FixedFilterValue::StringList(filters.life_cycle.as_deref())),
        "growth_rate" => Some(FixedFilterValue::StringList(filters.growth_rate.as_deref())),
        "edible" => Some(FixedFilterValue::Boolean(filters.edible)),
        "edibility_min" => Some(FixedFilterValue::Integer(filters.edibility_min)),
        "nitrogen_fixer" => Some(FixedFilterValue::Boolean(filters.nitrogen_fixer)),
        "family" => Some(FixedFilterValue::Text(filters.family.as_ref())),
        "climate_zones" => Some(FixedFilterValue::StringList(
            filters.climate_zones.as_deref(),
        )),
        "habit" => Some(FixedFilterValue::StringList(filters.habit.as_deref())),
        "woody" => Some(FixedFilterValue::Boolean(filters.woody)),
        _ => None,
    }
}

pub(crate) fn filter_field(key: &str) -> Option<&'static PlantFilterField> {
    match key {
        "stratum" => Some(&PLANT_FILTER_FIELDS[0]),
        "woody" => Some(&PLANT_FILTER_FIELDS[1]),
        "habit" => Some(&PLANT_FILTER_FIELDS[2]),
        "growth_form_type" => Some(&PLANT_FILTER_FIELDS[3]),
        "growth_form_shape" => Some(&PLANT_FILTER_FIELDS[4]),
        "growth_habit" => Some(&PLANT_FILTER_FIELDS[5]),
        "canopy_position" => Some(&PLANT_FILTER_FIELDS[6]),
        "deciduous_evergreen" => Some(&PLANT_FILTER_FIELDS[7]),
        "resprout_ability" => Some(&PLANT_FILTER_FIELDS[8]),
        "coppice_potential" => Some(&PLANT_FILTER_FIELDS[9]),
        "active_growth_period" => Some(&PLANT_FILTER_FIELDS[10]),
        "hardiness_zone_min" => Some(&PLANT_FILTER_FIELDS[11]),
        "hardiness_zone_max" => Some(&PLANT_FILTER_FIELDS[12]),
        "height_max_m" => Some(&PLANT_FILTER_FIELDS[13]),
        "frost_tender" => Some(&PLANT_FILTER_FIELDS[14]),
        "drought_tolerance" => Some(&PLANT_FILTER_FIELDS[15]),
        "soil_ph_min" => Some(&PLANT_FILTER_FIELDS[16]),
        "soil_ph_max" => Some(&PLANT_FILTER_FIELDS[17]),
        "tolerates_acid" => Some(&PLANT_FILTER_FIELDS[18]),
        "tolerates_alkaline" => Some(&PLANT_FILTER_FIELDS[19]),
        "tolerates_saline" => Some(&PLANT_FILTER_FIELDS[20]),
        "tolerates_wind" => Some(&PLANT_FILTER_FIELDS[21]),
        "tolerates_pollution" => Some(&PLANT_FILTER_FIELDS[22]),
        "tolerates_nutritionally_poor" => Some(&PLANT_FILTER_FIELDS[23]),
        "fertility_requirement" => Some(&PLANT_FILTER_FIELDS[24]),
        "moisture_use" => Some(&PLANT_FILTER_FIELDS[25]),
        "anaerobic_tolerance" => Some(&PLANT_FILTER_FIELDS[26]),
        "root_depth_min_cm" => Some(&PLANT_FILTER_FIELDS[27]),
        "frost_free_days_min" => Some(&PLANT_FILTER_FIELDS[28]),
        "precip_min_inches" => Some(&PLANT_FILTER_FIELDS[29]),
        "precip_max_inches" => Some(&PLANT_FILTER_FIELDS[30]),
        "succession_stage" => Some(&PLANT_FILTER_FIELDS[31]),
        "ecological_system" => Some(&PLANT_FILTER_FIELDS[32]),
        "mycorrhizal_type" => Some(&PLANT_FILTER_FIELDS[33]),
        "grime_strategy" => Some(&PLANT_FILTER_FIELDS[34]),
        "allelopathic" => Some(&PLANT_FILTER_FIELDS[35]),
        "root_system_type" => Some(&PLANT_FILTER_FIELDS[36]),
        "attracts_wildlife" => Some(&PLANT_FILTER_FIELDS[37]),
        "cn_ratio" => Some(&PLANT_FILTER_FIELDS[38]),
        "raunkiaer_life_form" => Some(&PLANT_FILTER_FIELDS[39]),
        "photosynthesis_pathway" => Some(&PLANT_FILTER_FIELDS[40]),
        "ellenberg_light" => Some(&PLANT_FILTER_FIELDS[41]),
        "ellenberg_temperature" => Some(&PLANT_FILTER_FIELDS[42]),
        "ellenberg_moisture" => Some(&PLANT_FILTER_FIELDS[43]),
        "ellenberg_reaction" => Some(&PLANT_FILTER_FIELDS[44]),
        "ellenberg_nitrogen" => Some(&PLANT_FILTER_FIELDS[45]),
        "ellenberg_salt" => Some(&PLANT_FILTER_FIELDS[46]),
        "pollination_syndrome" => Some(&PLANT_FILTER_FIELDS[47]),
        "self_fertile" => Some(&PLANT_FILTER_FIELDS[48]),
        "reproductive_type" => Some(&PLANT_FILTER_FIELDS[49]),
        "sexual_system" => Some(&PLANT_FILTER_FIELDS[50]),
        "vegetative_spread_rate" => Some(&PLANT_FILTER_FIELDS[51]),
        "seed_spread_rate" => Some(&PLANT_FILTER_FIELDS[52]),
        "mating_system" => Some(&PLANT_FILTER_FIELDS[53]),
        "clonal_growth_form" => Some(&PLANT_FILTER_FIELDS[54]),
        "storage_organ" => Some(&PLANT_FILTER_FIELDS[55]),
        "bloom_period" => Some(&PLANT_FILTER_FIELDS[56]),
        "flower_color" => Some(&PLANT_FILTER_FIELDS[57]),
        "propagated_by_seed" => Some(&PLANT_FILTER_FIELDS[58]),
        "propagated_by_cuttings" => Some(&PLANT_FILTER_FIELDS[59]),
        "cold_stratification_required" => Some(&PLANT_FILTER_FIELDS[60]),
        "fruit_type" => Some(&PLANT_FILTER_FIELDS[61]),
        "seed_dispersal_mechanism" => Some(&PLANT_FILTER_FIELDS[62]),
        "seed_storage_behaviour" => Some(&PLANT_FILTER_FIELDS[63]),
        "fruit_seed_abundance" => Some(&PLANT_FILTER_FIELDS[64]),
        "seed_dormancy_type" => Some(&PLANT_FILTER_FIELDS[65]),
        "seed_dormancy_depth" => Some(&PLANT_FILTER_FIELDS[66]),
        "serotinous" => Some(&PLANT_FILTER_FIELDS[67]),
        "leaf_type" => Some(&PLANT_FILTER_FIELDS[68]),
        "leaf_compoundness" => Some(&PLANT_FILTER_FIELDS[69]),
        "leaf_shape" => Some(&PLANT_FILTER_FIELDS[70]),
        "toxicity" => Some(&PLANT_FILTER_FIELDS[71]),
        "invasive_potential" => Some(&PLANT_FILTER_FIELDS[72]),
        "biogeographic_status" => Some(&PLANT_FILTER_FIELDS[73]),
        "noxious_status" => Some(&PLANT_FILTER_FIELDS[74]),
        "invasive_usda" => Some(&PLANT_FILTER_FIELDS[75]),
        "weed_potential" => Some(&PLANT_FILTER_FIELDS[76]),
        "fire_resistant" => Some(&PLANT_FILTER_FIELDS[77]),
        "fire_tolerance" => Some(&PLANT_FILTER_FIELDS[78]),
        "medicinal_rating" => Some(&PLANT_FILTER_FIELDS[79]),
        "other_uses_rating" => Some(&PLANT_FILTER_FIELDS[80]),
        "scented" => Some(&PLANT_FILTER_FIELDS[81]),
        _ => None,
    }
}

pub(crate) fn validated_column(key: &str) -> Option<&'static str> {
    filter_field(key).map(|field| {
        debug_assert_eq!(field.key, key);
        field.column
    })
}

pub(crate) fn filter_field_kind(key: &str) -> Option<PlantFilterFieldKind> {
    filter_field(key).map(|field| field.kind)
}

#[cfg(test)]
pub(crate) fn fixed_filter_behavior(key: &str) -> Option<&'static FixedFilterBehavior> {
    match key {
        "sun_tolerances" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[0]),
        "soil_tolerances" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[1]),
        "life_cycle" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[2]),
        "growth_rate" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[3]),
        "edible" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[4]),
        "edibility_min" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[5]),
        "nitrogen_fixer" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[6]),
        "family" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[7]),
        "climate_zones" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[8]),
        "habit" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[9]),
        "woody" => Some(&SPECIES_FILTER_FIXED_BEHAVIORS[10]),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_known_columns_and_rejects_unknown_fields() {
        assert_eq!(validated_column("height_max_m"), Some("s.height_max_m"));
        assert_eq!(validated_column("climate_zones"), None);
        assert_eq!(validated_column("height_max_m; DROP TABLE species"), None);
    }

    #[test]
    fn exposes_field_kinds_from_schema() {
        assert_eq!(
            filter_field_kind("woody"),
            Some(PlantFilterFieldKind::Boolean)
        );
        assert_eq!(
            filter_field_kind("growth_form_type"),
            Some(PlantFilterFieldKind::Categorical)
        );
        assert_eq!(
            filter_field_kind("height_max_m"),
            Some(PlantFilterFieldKind::Numeric)
        );
        assert_eq!(filter_field_kind("not_a_field"), None);
    }

    #[test]
    fn generated_fields_keep_static_sql_allowlist_entries() {
        assert!(
            PLANT_FILTER_FIELDS
                .iter()
                .all(|field| field.column.starts_with("s."))
        );
        assert!(PLANT_FILTER_FIELDS.iter().any(|field| field.key == "habit"));
    }

    #[test]
    fn exposes_fixed_species_filter_behavior_from_schema() {
        let behavior = fixed_filter_behavior("life_cycle").unwrap();
        assert_eq!(behavior.key, "life_cycle");
        match behavior.predicate {
            FixedFilterPredicate::MappedBooleanList(clauses) => {
                assert!(clauses.iter().any(|clause| clause.value == "Perennial"));
            }
            _ => panic!("expected mapped boolean predicate"),
        }
        assert!(fixed_filter_behavior("not_a_field").is_none());
    }

    #[test]
    fn generated_fixed_filters_read_species_filter_values() {
        let filters = common_types::species::SpeciesFilter {
            life_cycle: Some(vec!["Perennial".to_owned()]),
            nitrogen_fixer: Some(true),
            edibility_min: Some(3),
            family: Some("Rosaceae".to_owned()),
            ..common_types::species::SpeciesFilter::default()
        };

        match fixed_filter_value(&filters, "life_cycle").unwrap() {
            FixedFilterValue::StringList(Some(values)) => {
                assert_eq!(values, ["Perennial".to_owned()].as_slice())
            }
            other => panic!("expected life_cycle list, got {other:?}"),
        }
        assert!(matches!(
            fixed_filter_value(&filters, "nitrogen_fixer"),
            Some(FixedFilterValue::Boolean(Some(true)))
        ));
        assert!(matches!(
            fixed_filter_value(&filters, "edibility_min"),
            Some(FixedFilterValue::Integer(Some(3)))
        ));
        match fixed_filter_value(&filters, "family").unwrap() {
            FixedFilterValue::Text(Some(value)) => assert_eq!(value, "Rosaceae"),
            other => panic!("expected family text, got {other:?}"),
        }
    }
}
